//
//	You may customize this code as you like
//	Report bugs to: https://silentorbit.com/protobuf/
//
//	Generated by ProtocolBuffer
//	- a pure c# code generation implementation of protocol buffers
//

using System;
using System.Collections.Generic;

namespace Whisper.Encryption
{
	public partial class KeysHeader
	{
		//public byte[] IV { get; set; }	//Implemented by user elsewhere
		//public List<byte[]> EncryptedKeys { get; set; }	//Implemented by user elsewhere
	}

}
