//
//	You may customize this code as you like
//	Report bugs to: https://silentorbit.com/protobuf/
//
//	Generated by ProtocolBuffer
//	- a pure c# code generation implementation of protocol buffers
//

using System;
using System.Collections.Generic;

namespace Whisper.Messages
{
	public partial class TrippleID
	{
		protected byte[] ChunkHashBytes { get; set; }
		protected byte[] CustomIdBytes { get; set; }
		protected byte[] ClearHashBytes { get; set; }
	
		//protected virtual void BeforeSerialize() {}
		//protected virtual void AfterDeserialize() {}
	}

}
namespace Whisper.ChunkGenerator
{
	public partial class StreamChunk
	{
		public ulong Size { get; set; }
		public List<Whisper.Messages.TrippleID> Chunks { get; set; }
	}

}
namespace Whisper.ChunkGenerator
{
	public partial class TreeFile
	{
		public string Name { get; set; }
		public Whisper.Messages.TrippleID TreeChunkID { get; set; }
	}

}
namespace Whisper.ChunkGenerator
{
	public partial class TreeChunk
	{
		public List<Whisper.ChunkGenerator.TreeFile> Directories { get; set; }
		public List<Whisper.ChunkGenerator.TreeFile> Files { get; set; }
	}

}
namespace Whisper.Messages
{
	/// <summary>
	/// Chunk Messages
	/// </summary>
	public partial class MessageHeader
	{
		public uint MessageId { get; set; }
		public byte[] Signature { get; set; }
	}

}
namespace Whisper.Messages
{
	/// <summary>
	/// MessageID = 1
	/// </summary>
	public partial class TreeMessage
	{
		public string Name { get; set; }
		public Whisper.Messages.TrippleID TreeChunkID { get; set; }
	}

}
namespace Whisper.Messages
{
	/// <summary>
	/// MessageID = 2
	/// </summary>
	public partial class RouteMessage
	{
		/// <summary>
		///  What to send
		/// </summary>
		public byte[] MessageChunkHash { get; set; }
		/// <summary>
		///  Where to send it
		/// </summary>
		public string To { get; set; }
		/// <summary>
		///  All the chunks going with that message
		/// </summary>
		public List<byte[]> Chunks { get; set; }
	}

}
namespace Whisper.Messages
{
	/// <summary>
	/// MessageID = 3
	/// </summary>
	public partial class ListMessage
	{
		public List<Whisper.Messages.TrippleID> List { get; set; }
	}

}
